name: myflow1a

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  mybuild1:
    runs-on: ubuntu-latest
    # environment: prod1
    environment: ${{ github.event.ref == 'refs/heads/main' && 'prod1' || 'dev1' }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: test
      env:
        MYSECRET1VAR: ${{ secrets.MYSECRET1 }} 
      run: |
        echo $PATH | tr ':' '\n'
        echo "branch display"
        git branch
        echo "=============="
        echo "The current22 environment is ${{ job.environment.name }}"
        echo "=============="
        echo "try to display secret mysecret1"
        echo "xxx${{ secrets.MYSECRET1}}yyy"
        echo "try to display env var  mysecret1var"
        echo "xxx${MYSECRET1VAR}yyy"
        if [ "$MYSECRET1VAR" = "prodxaxa1" ]; then
          echo "The variable matches prod1 "
        elif [ "$MYSECRET1VAR" = "devxaxa1" ]; then
          echo "The variable matches dev1 "
        else
          echo "The variable does not match "
        fi        

