name: myflow1a

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  mybuild1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: test

      run: |
        echo $PATH | tr ':' '\n'
        echo "branch display"
        git branch
        echo "mysecret1"
        echo ${{ secrets.MYSECRET1}}

